// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "crochets.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

crochets::crochets() : Subsystem("crochets") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	pot = RobotMap::crochetspot;
	moteurCrochets = RobotMap::crochetsmoteurCrochets;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void crochets::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

bool crochets::MaxAtteint(){
	if(pot->Get()>0.8){
		return true;
	}
	else{
		return false;
	}
}

bool crochets::MinAtteint(){
	if(pot->Get()<0.08){
		return true;
	}
	else{
		return false;
	}

}

/*
void crochets::ValeursPot(){
	SmartDashboard->PutNumber("Potentiomètre",pot->Get());
}
*/
void crochets::MoteurUp(){
	Robot::crochets->moteurCrochets->Set(1);
}
void crochets::MoteurDown(){
	Robot::crochets->moteurCrochets->Set(-1);
}
void crochets::MoteurStop(){
	Robot::crochets->moteurCrochets->Set(0);
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

