// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CROCHETS_H
#define CROCHETS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Crochets: public Subsystem {

	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	AnalogPotentiometer* pot;
	SpeedController* moteurCrochets;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

public:
	Crochets();
	void InitDefaultCommand();
	bool MaxAtteint();
	bool MinAtteint();
	void ValeursPot();
	void MoteurUp();
	void MoteurDown();
	void MoteurStop();
};

#endif
