// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::basePilotabledriveG = NULL;
SpeedController* RobotMap::basePilotabledriveD = NULL;
RobotDrive* RobotMap::basePilotabledrive = NULL;
AnalogPotentiometer* RobotMap::crochetspot = NULL;
SpeedController* RobotMap::crochetsmoteurCrochets = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	basePilotabledriveG = new Victor(2);
	lw->AddActuator("basePilotable", "driveG", (Victor*) basePilotabledriveG);
	
	basePilotabledriveD = new Victor(4);
	lw->AddActuator("basePilotable", "driveD", (Victor*) basePilotabledriveD);
	
	basePilotabledrive = new RobotDrive(basePilotabledriveG, basePilotabledriveD);
	
	basePilotabledrive->SetSafetyEnabled(true);
        basePilotabledrive->SetExpiration(0.1);
        basePilotabledrive->SetSensitivity(0.5);
        basePilotabledrive->SetMaxOutput(1.0);
        

	crochetspot = new AnalogPotentiometer(0, 1.0, 0.0);
	lw->AddSensor("crochets", "pot", crochetspot);
	
	crochetsmoteurCrochets = new Talon(0);
	lw->AddActuator("crochets", "moteurCrochets", (Talon*) crochetsmoteurCrochets);
	


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
